version: 1.0.{build}
image: Visual Studio 2017
install:
- git clone https://github.com/HumMan/RDPCertInstaller.git
- nuget restore RDPCertInstaller.sln
build:
  project: RDPCertInstaller.sln
  verbosity: minimal
artifacts:
- path: bin\x86\Debug\
  name: RDPCertInstaller
  type: zip